name: competition
channels:
  - defaults
dependencies:
  - pip=23.2.1
  - python=3.11.4
  - pip:
      - alembic==1.11.1
      - catboost==1.2
      - cmaes==0.10.0
      - colorlog==6.7.0
      - contourpy==1.1.0
      - cycler==0.11.0
      - dataliner==1.3.1
      - fonttools==4.41.1
      - geographiclib==2.0
      - geopy==2.3.0
      - greenlet==2.0.2
      - joblib==1.3.1
      - kiwisolver==1.4.4
      - lightgbm==4.0.0
      - mako==1.2.4
      - markupsafe==2.1.3
      - matplotlib==3.7.2
      - mojimoji==0.0.12
      - numpy==1.25.2
      - optuna==3.2.0
      - pandas==2.0.3
      - pillow==10.0.0
      - plotly==5.15.0
      - polars==0.18.11
      - pyparsing==3.0.9
      - python-graphviz==0.20.1
      - pytz==2023.3
      - pyyaml==6.0.1
      - rgf-python==3.12.0
      - scikit-learn==1.3.0
      - scipy==1.11.1
      - seaborn==0.12.2
      - sqlalchemy==2.0.19
      - tenacity==8.2.2
      - threadpoolctl==3.2.0
      - tqdm==4.65.0
      - typing-extensions==4.7.1
      - tzdata==2023.3
      - xgboost==1.7.6
